spring:
  datasource:
    username: MYJAVA
    password: 1234
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
    driver-class-name: oracle.jdbc.OracleDriver

server:
  port: 8081

#dubbo:
#  application:
#    name: springboot-02-web-dubbo-service
#  registry:
#    address: 127.0.0.1:2181
#    protocol: zookeeper
#  protocol:
#    name: dubbo
#    port: 20080
dubbo:
  application:
    name: springboot-02-web-dubbo-service
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20080

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.anzaiyun.api.dao
